- name: demo on printing
  hosts: localhost
  tasks:
    - name: print hello world
      ansible.builtin.debug:
        msg: hello world

- name: demo on vars
  hosts: localhost
  vars:
    url: example.com
  tasks:
    - name: print a variable
      ansible.builtin.debug:
        msg: "{{url}}"

- name: demo on task level vars
  hosts: localhost
  tasks:
    - name: print a variable
      ansible.builtin.debug:
        msg: "{{url}}"
      vars:
        url: example.com

- name: demo on task level vars
  hosts: localhost
  vars:
    url: play.example.com
  tasks:
    - name: print task variable
      ansible.builtin.debug:
        msg: "{{url}}"
      vars:
        url: task.example.com

    - name: print play variable
      ansible.builtin.debug:
        msg: "{{url}}"


- name: demo on variable not defined
  hosts: localhost
  vars:
    url: play.example.com
  tasks:
    - name: print task variable
      ansible.builtin.debug:
        msg: "{{url}}"
      vars:
        url: task.example.com

    - name: print play variable
      ansible.builtin.debug:
        msg: "{{url1}}"



